; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c6-devkitc-1]
platform = espressif32
board = esp32-c6-devkitc-1  ; 使用一个最接近的开发板作为基础
framework = espidf

; 连接配置
monitor_speed = 115200
upload_speed = 921600
; upload_port = COM25

; WiFi 6/6E 关键配置
build_flags = 
    -DCONFIG_ESP_WIFI_11AX_ENABLED=y    ; 启用 802.11ax
    -DCONFIG_ESP_WIFI_11N_ENABLED=y     ; 启用 802.11n
    -DCONFIG_ESP_PHY_ENABLE_USB=y       ; USB PHY 校准
    -DCONFIG_ESP_WIFI_CHANNEL_MAX=13    ; 2.4GHz 最大信道
    -DCONFIG_ESP_WIFI_AMPDU_ENABLED=y   ; 启用帧聚合
    ;-DCONFIG_FREERTOS_USE_TICKLESS_IDLE=n
    
; 监控配置
monitor_filters = direct                ; 禁用 PlatformIO 的默认过滤器
